name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
    testJob:
        runs-on: macos-11
        steps:
          - uses: actions/checkout@v2
          - run: npm install
          - run: npm cache clean --force
          - run: npm check-rules
